spring:
  rabbitmq:
    host: rabbit.mq.middle.jemmyweb.com
    port: 5672
    username: guest
    password: guest
    virtual-host: jemmyweb
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    banner-mode: "OFF"
server:
  port: 6010

