spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: jemmyweb
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  main:
    banner-mode: "OFF"

