spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      service-id: service-user
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    mdc-route:
      path: /mdc/**
      sensitiveHeaders:
      service-id: service-product
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    opc-route:
      path: /opc/**
      sensitiveHeaders:
      service-id: service-opc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
    tpc-route:
      path: /tpc/**
      sensitiveHeaders:
      service-id: service-edriven
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
  add-proxy-headers: true
  add-host-header: true

security:
  oauth2:
    client:
      clientId: client-infras-gw
      clientSecret: oauth2ClientSecret
      access-token-uri: http://api.infras.jemmyweb.com:6030/uac/oauth/token
      user-authorization-uri: http://api.infras.jemmyweb.com:6030/uac/oauth/authorize
    resource:
      user-info-uri: http://api.infras.jemmyweb.com:6030/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://user.service.jemmyweb.com:6020/oauth/token_key

proxy:
  auth:
    routes:
      uac-route: oauth2
      mdc-route: oauth2

jemmycloud:
  enableSqlLogInterceptor: false
# swagger butler配置
swagger.butler:
  api-docs-path: v2/api-docs?group=前端调用接口
  swagger-version: 1.0
  auto-generate-from-zuul-routes: true
# 指定要生成的范围
#  generate-routes: mdc-route,opc-route,tpc-route,uac-route
# 忽略某些路由生成
  ignore-routes: infras-gw,infras-config,infras-center,infras-monitor,infras-zipkin,tx-manager,txmanager-route
  #swagger资源配置
  resources:
    uac-route:
      name: 用户服务-前端调用接口
    service-user:
      name: 用户服务-服务间调用接口
      api-docs-path: v2/api-docs?group=微服务间调用接口
    mdc-route:
      name: 产品服务-前端调用接口
    service-product:
      name: 产品服务-服务间调用接口
      api-docs-path: v2/api-docs?group=微服务间调用接口
    opc-route:
      name: 开放平台-前端调用接口
    service-opc:
      name: 开放平台-服务间调用接口
      api-docs-path: v2/api-docs?group=微服务间调用接口
    tpc-route:
      name: 可靠消息服务-前端调用接口
    service-edriven:
      name: 可靠消息服务-服务间调用接口
      api-docs-path: v2/api-docs?group=微服务间调用接口
