spring:
  mvc:
    favicon:
      enabled: false
    #当找不到可处理的handler时,应该抛出异常,否则将会直接将结果写入response,导致不可以被异常处理机制拦截
    throw-exception-if-no-handler-found: true
    locale-resolver: fixed
    locale: zh_CN
  resources:
    add-mappings: false
  messages:
      basename: classpath:org/springframework/security/messages
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
    virtual-host: jemmyweb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  main:
    banner-mode: "OFF"
server:
  tomcat:
    max-threads: 1500
    max-connections: 600
    min-spare-threads: 1500
    accept-count: 100
zuul:
  ignored-services: center,config,monitor,gw
  #禁止转发度量接口
  ignored-patterns: /*/info,/*/loggers,/*/metrics,/*/health,/*/mappings,/*/beans,/*/dump,/*/heapdump,/*/env,/*/configprops,/*/trace,/*/loadBalancer,/*/bizConfig,/*/instance-status,/*/hystrix.stream,/*/service-registry
  sensitive-headers:
  host:
    connect-timeout-millis: 120000
    socket-timeout-millis: 120000
    max-total-connections: 5000
    max-per-route-connections: 1000
  retryable: true
  ###hystrix配置begin###
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: gw
  ###hystrix配置end###
  SendErrorFilter:
    error:
      disable: true
#超时配置
ribbon:
  client:
    #name: client
  httpclient:
    enabled: true
  ReadTimeout: 36000
  ConnectTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  MaxHttpConnectionsPerHost: 1000
  MaxTotalConnections: 5000
  MaxTotalHttpConnections: 5000
  MaxConnectionsPerHost: 1000
  PoolMaxThreads: 8000
  PoolMinThreads: 5000
hystrix:
  shareSecurityContext: true
  metrics:
    enabled: true
  threadpool:
    default:
      coreSize: 5000
      maxQueueSize: 5000
      queueSizeRejectionThreshold: 4500
  command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            strategy: THREAD
            #设置所有的hystrix超时时间,其值应大于ribbon的超时时长,并注意考虑ribbon重试所花云的时长. 否则,一旦hystrix超时,整个服务将超时#
            thread:
              timeoutInMilliseconds: 150000
        fallback:
          isolation.semaphore.maxConcurrentRequests: 30000
        circuitBreaker:
          requestVolumeThreshold: 3000
          sleepWindowInMilliseconds: 1000
          errorThresholdPercentage: 60
#去掉x-application-header响应头
management:
  add-application-context-header: false
  security:
    enabled: false
#禁止向外展示路由
endpoints:
  routes:
    enabled: false
  actuator:
    sensitive: true
security:
  oauth2:
    client:
      client-id: gw
      client-secret: 123456
      access-token-uri: http://localhost:9040/oauth/token
      user-authorization-uri: http://localhost:9040/oauth/authorize
      authentication-scheme: header
      client-authentication-scheme: header
    resource:
      token-info-uri: http://localhost:9040/oauth/check_token
      prefer-token-info: false
      #若使用jwt令牌,则token-info-uri无效,使用以下配置
      jwt:
        key-value: demo
      user-info-uri: http://localhost:9040/order/info
      id: ${spring.application.name}
      filter-order: 3
    sso:
      login-path: http://localhost:9030/user/sso/login
  sessions: stateless
  basic:
    enabled: false
    realm: zk24j
  enable-csrf: false
proxy:
  auth:
    load-balanced: true
#程序访问控制
com.jemmy:
  gw:
    urls:
      permitall: /user/oauth/token,/user/sso/login
  headers:
    cors: '*'