spring:
  datasource:
    url: jdbc:mysql://paascloud-db-mysql:3306/paascloud_zipkin?characterEncoding=utf8&useSSL=false
    schema: classpath:/mysql.sql
  sleuth:
    enabled: false
  zipkin:
    locator:
      discovery:
        enabled: true

zipkin:
  collector:
    rabbitmq:
      addresses: paascloud-mq-rabbit:5672
      username: guest
      password: guest
      queue: zipkin
  storage:
    type: mysql

security:
  oauth2:
    client:
      clientId: client-infras-monitor
      clientSecret: oauth2ClientSecret
      access-token-uri: http://paascloud-gateway:7030/uac/oauth/token
      user-authorization-uri: http://paascloud-gateway:7030/uac/oauth/authorize
    resource:
      user-info-uri: http://paascloud-gateway:7030/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://paascloud-provider-uac:7020/oauth/token_key

jemmycloud:
  oauth2:
    client:
      id: ${security.oauth2.resource.id}
      accessTokenUrl: ${security.oauth2.client.access-token-uri}
      clientId: ${security.oauth2.client.clientId}
      clientSecret: ${security.oauth2.client.clientSecret}
      clientAuthenticationScheme: header
      tokenStore: jwt