version: "3"
#service.version=1.0-SNAPSHOT
services:
    center1:
        image: jemmyweb/infras-center:1.0-SNAPSHOT
        ports:
          - '6001:6001'
        expose:
          - '6001'
        hostname: "center1.infras.jemmyweb.com"
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9901 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9901 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.profiles.active=peer1'
        networks:
          - app_net
    center2:
        image: jemmyweb/infras-center:1.0-SNAPSHOT
        hostname: "center2.infras.jemmyweb.com"
        expose:
            - "6002"
        links:
            - "center1:center1.infras.jemmyweb.com"
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9902 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9902 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.profiles.active=peer2'
        networks:
          - app_net
    config:
        image: jemmyweb/infras-config:1.0-SNAPSHOT
        ports:
          - "6010:6010"
        expose:
            - "6010"
        hostname: "config.infras.jemmyweb.com"
        links:
            - "center1:center1.infras.jemmyweb.com"
        external_links:
          - 'rabbit:rabbit.mq.middle.jemmyweb.com'
        depends_on:
          - center1
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: '-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9910 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9910 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
networks:
  app_net:
    external: true