version: "3"
#service.version=1.0-SNAPSHOT
services:
    center1:
        image: jemmyweb/center:1.0-SNAPSHOT
        ports:
            - "9001:9001"
            - "9901:9901"
        hostname: center1.jemmy.com
        links:
            - center2
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9901 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9901 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.application.index=0 --server.port=9001 --spring.profiles.active=peer1 --eureka.client.serviceUrl.defaultZone=http://center2:9002/eureka/  --eureka.client.serviceUrl.zone1=http://center2:9002/eureka/ '
    center2:
        image: jemmyweb/center:1.0-SNAPSHOT
        ports:
            - "9002:9002"
            - "9902:9902"
        hostname: center2.jemmy.com
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9902 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9902 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.application.index=1 --server.port=9002 --spring.profiles.active=peer2  --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '
    config:
        image: jemmyweb/config:1.0-SNAPSHOT
        ports:
            - "9010:9010"
            - "9910:9910"
        hostname: config.jemmy.com
        depends_on:
            - 'center1'
            - 'center2'
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9010/health"]
           interval: 30s
           timeout: 30s
           retries: 3
        links:
            - center1
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: '-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9910 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9910 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
            PARAMS: '--spring.application.index=0 --server.port=9010 --spring.rabbitmq.host=192.168.99.100 --spring.profiles.active=test   --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '
    monitor:
        image: jemmyweb/monitor:1.0-SNAPSHOT
        ports:
            - "9090:9090"
            - "9990:9990"
        hostname: monitor.jemmy.com
        depends_on:
            - 'center1'
            - 'center2'
            - 'config'
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
           interval: 30s
           timeout: 30s
           retries: 3
        links:
          - center1
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: '-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9990 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9990 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
            PARAMS: '--spring.application.index=0 --server.port=9090 --spring.rabbitmq.host=192.168.99.100 --spring.profiles.active=test --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '