version: "3"
#service.version=1.0-SNAPSHOT
services:
    center1:
        image: jemmyweb/infras-center:1.0-SNAPSHOT
        ports:
          - '6001:6001'
        expose:
          - '6001'
        hostname: "center1.infras.jemmyweb.com"
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9901 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9901 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.profiles.active=peer1'
        networks:
          - app_net
    center2:
        image: jemmyweb/infras-center:1.0-SNAPSHOT
        hostname: "center2.infras.jemmyweb.com"
        expose:
            - "6002"
        links:
            - "center1:center1.infras.jemmyweb.com"
        environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: '-Xms128m -Xmx128m -Dcom.sun.management.jmxremote.rmi.port=9902 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9902 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
          PARAMS: '--spring.profiles.active=peer2'
        networks:
          - app_net
    config:
        image: jemmyweb/infras-config:1.0-SNAPSHOT
        expose:
            - "6010"
        hostname: "config.infras.jemmyweb.com"
        links:
            - "center1:center1.infras.jemmyweb.com"
        external_links:
          - 'rabbit:rabbit.mq.middle.jemmyweb.com'
        depends_on:
          - center1
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: '-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9910 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9910 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100'
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
    user:
        image: jemmyweb/service-user:1.0-SNAPSHOT
        expose:
            - "6020"
        depends_on:
          - config
        #deploy:
          #mode: replicated
          #replicas: 2
        healthcheck:
           test: ["CMD", "curl", "-f", "http://user:6020/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: user.service.jemmyweb.com
        links:
          - "config:config.infras.jemmyweb.com"
          - "center1:center1.infras.jemmyweb.com"
        external_links:
          - 'redis:redis.db.middle.jemmyweb.com'
          - 'mysql:mysql.db.middle.jemmyweb.com'
          - 'rabbit:rabbit.mq.middle.jemmyweb.com'
          - 'rocketmq:rocket.mq.middle.jemmyweb.com'
          - 'zookeeper:zk.server.middle.jemmyweb.com'
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9940 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9940 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
networks:
  app_net:
    external: true