version: "3"

services:
    rabbit:
        image: rabbitmq:3-management
        ports:
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
        hostname: rabbit
        environment:
            - TZ=Asia/Shanghai
            - RABBITMQ_DEFAULT_USER=test
            - RABBITMQ_DEFAULT_PASS=test
            - RABBITMQ_DEFAULT_VHOST=zj24k
    redis:
        image: redis
        ports:
            - "6379:6379"
        hostname: redis
    mysql:
        image: mysql:5.7.22
        hostname: mysql
        ports:
            - "3306:3306"
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_ROOT_PASSWORD=123456