version: "3"

services:
    order:
        image: jemmyweb/order:1.0-SNAPSHOT
        ports:
            - "9020:9020"
            - "9920:9920"
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9020/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: order.jemmy.com
        external_links:
           - center1
          - product
          - third
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9920 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9920 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.application.index=0 --server.port=9020 --spring.profiles.active=test --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '