version: "3"

services:
    product:
            image: jemmyweb/service-product:1.0-SNAPSHOT
            expose:
              - 6050
            healthcheck:
               test: ["CMD", "curl", "-f", "http://product:9050/health"]
               interval: 10s
               timeout: 5s
               retries: 3
            hostname: product.service.jemmyweb.com
            external_links:
               - center1
               - edriven
               - "user:user.service.jemmyweb.com"
               - config
               - 'redis:redis.db.middle.jemmyweb.com'
               - 'mysql:mysql.db.middle.jemmyweb.com'
               - 'rabbit:rabbit.mq.middle.jemmyweb.com'
               - 'rocketmq:rocket.mq.middle.jemmyweb.com'
               - 'zookeeper:zk.server.middle.jemmyweb.com'
            environment:
                TZ: Asia/Shanghai
                JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9950 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9950 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
                PARAMS: '--spring.profiles.active=devt'
            networks:
              - app_net
networks:
  app_net:
    external: true