version: "3"

services:
    gw:
      image: jemmyweb/infras-gw:1.0-SNAPSHOT
      ports:
          - "6030:6030"
      expose:
        - 6030
      healthcheck:
         test: ["CMD", "curl", "-f", "http://gw:6030/health"]
         interval: 30s
         timeout: 30s
         retries: 3
      hostname: api.infras.jemmyweb.com
      links:
        - product
        - opc
        - edriven
      external_links:
         - center1
         - config
         - "user:user.service.jemmyweb.com"
         - 'rabbit:rabbit.mq.middle.jemmyweb.com'
      environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9930 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9930 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
          PARAMS: '--spring.profiles.active=devt --spring.rabbitmq.host=rabbit'
      networks:
        - app_net
    product:
        image: jemmyweb/service-product:1.0-SNAPSHOT
        expose:
          - 6050
        healthcheck:
           test: ["CMD", "curl", "-f", "http://product:9050/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: product.service.jemmyweb.com
        links:
           - edriven
        external_links:
           - center1
           - user:user.service.jemmyweb.com"
           - config
           - 'redis:redis.db.middle.jemmyweb.com'
           - 'mysql:mysql.db.middle.jemmyweb.com'
           - 'rabbit:rabbit.mq.middle.jemmyweb.com'
           - 'rocketmq:rocket.mq.middle.jemmyweb.com'
           - 'zookeeper:zk.server.middle.jemmyweb.com'
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9950 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9950 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
    edriven:
        image: jemmyweb/service-edriven:1.0-SNAPSHOT
        expose:
          - 6060
        healthcheck:
           test: ["CMD", "curl", "-f", "http://edriven:6060/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: edriven.service.jemmyweb.com
        external_links:
           - center1
           - "user:user.service.jemmyweb.com"
           - config
           - 'redis:redis.db.middle.jemmyweb.com'
           - 'mysql:mysql.db.middle.jemmyweb.com'
           - 'rabbit:rabbit.mq.middle.jemmyweb.com'
           - 'rocketmq:rocket.mq.middle.jemmyweb.com'
           - 'zookeeper:zk.server.middle.jemmyweb.com'
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9950 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9950 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
    opc:
        image: jemmyweb/service-opc:1.0-SNAPSHOT
        expose:
          - 6040
        healthcheck:
           test: ["CMD", "curl", "-f", "http://opc:6040/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: opc.service.jemmyweb.com
        links:
           - edriven
        external_links:
           - center1
           - "user:user.service.jemmyweb.com"
           - config
           - 'redis:redis.db.middle.jemmyweb.com'
           - 'mysql:mysql.db.middle.jemmyweb.com'
           - 'rabbit:rabbit.mq.middle.jemmyweb.com'
           - 'rocketmq:rocket.mq.middle.jemmyweb.com'
           - 'zookeeper:zk.server.middle.jemmyweb.com'
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9950 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9950 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.profiles.active=devt'
        networks:
          - app_net
networks:
  app_net:
    external: true
