version: "3"

services:
    api:
      image: jemmyweb/api:1.0-SNAPSHOT
      ports:
          - "9030:9030"
          - "9930:9930"
      healthcheck:
         test: ["CMD", "curl", "-f", "http://localhost:9030/health"]
         interval: 30s
         timeout: 30s
         retries: 3
      hostname: api.jemmyweb.com
      external_links:
         - center1
      environment:
          TZ: Asia/Shanghai
          JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9930 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9930 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
          PARAMS: '--spring.application.index=0 --server.port=9030 --spring.profiles.active=devt --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '
    order:
        image: jemmyweb/order:1.0-SNAPSHOT
        ports:
            - "9020:9020"
            - "9920:9920"
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9020/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: order.jemmyweb.com
        external_links:
           - center1
        links:
          - product
          - third
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9920 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9920 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.application.index=0 --server.port=9020 --spring.profiles.active=devt --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '
    product:
        image: jemmyweb/product:1.0-SNAPSHOT
        ports:
            - "9050:9050"
            - "9950:9950"
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9050/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: product.jemmyweb.com
        external_links:
           - center1
        links:
          - third
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9950 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9950 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.application.index=0 --server.port=9050 --spring.profiles.active=devt --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '
    user:
        image: jemmyweb/user:1.0-SNAPSHOT
        ports:
            - "9040:9040"
            - "9940:9940"
        deploy:
          mode: replicated
          replicas: 2
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9040/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: user.jemmyweb.com
        external_links:
          - center1
        links:
          - third:third.jemmyweb.com
          - order:order.jemmyweb.com
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms512m -Xmx512m -Dcom.sun.management.jmxremote.rmi.port=9940 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9940 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.application.index=0 --server.port=9040 --spring.profiles.active=devt --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '