version: "3"

services:
    user:
        image: jemmyweb/user:1.0-SNAPSHOT
        ports:
            - "9040:9040"
            - "9940:9940"
        deploy:
          mode: replicated
          replicas: 2
        healthcheck:
           test: ["CMD", "curl", "-f", "http://localhost:9040/health"]
           interval: 10s
           timeout: 5s
           retries: 3
        hostname: user.jemmy.com
        external_links:
          - center1
          - third:third.jemmy.com
          - order:order.jemmy.com
        environment:
            TZ: Asia/Shanghai
            JAVA_OPTS: "-Xms256m -Xmx256m -Dcom.sun.management.jmxremote.rmi.port=9940 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9940 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=192.168.99.100"
            PARAMS: '--spring.application.index=0 --server.port=9040 --spring.profiles.active=devt --eureka.client.serviceUrl.defaultZone=http://center1:9001/eureka/  --eureka.client.serviceUrl.zone1=http://center1:9001/eureka/ '